language: python

python:
  - "2.7"

script:
 - ./channelmerge

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TRAVIS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
